-- ============================================================================
-- MiniDocker - Database Schema DDL (Oracle SQL / PL-SQL)
-- ============================================================================
-- Academic Focus:
-- 1. Relational Schema Design & 3NF Normalization
-- 2. Primary Key & Referential Integrity (Foreign Keys with ON DELETE CASCADE)
-- 3. Domain Integrity (CHECK constraints, DEFAULT values, NOT NULL)
-- 4. B-Tree Indexing on High-Cardinality and Foreign Key Columns
-- ============================================================================

-- Clean up existing database objects if re-running
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE resource_usage CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE process_logs CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE containers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================================
-- TABLE: users
-- Represents operators and team members running container workloads
-- ============================================================================
CREATE TABLE users (
    user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR2(50) NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username)
);

-- ============================================================================
-- TABLE: containers
-- Master entity representing an OS process tracked as a container workload
-- ============================================================================
CREATE TABLE containers (
    container_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    container_name VARCHAR2(100) NOT NULL,
    command        VARCHAR2(500) NOT NULL,
    pid            NUMBER,
    status         VARCHAR2(20) DEFAULT 'CREATED' NOT NULL,
    cpu_limit      NUMBER DEFAULT 0,       -- Limit in CPU seconds (0 = unlimited)
    memory_limit   NUMBER DEFAULT 0,       -- Limit in Bytes (0 = unlimited)
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_container_name UNIQUE (container_name),
    CONSTRAINT chk_container_status CHECK (
        status IN ('CREATED', 'RUNNING', 'STOPPED', 'EXITED', 'FAILED')
    )
);

-- ============================================================================
-- TABLE: process_logs
-- Immutable audit ledger recording container lifecycle state transitions
-- ============================================================================
CREATE TABLE process_logs (
    log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    container_id  NUMBER NOT NULL,
    action        VARCHAR2(100) NOT NULL,
    old_status    VARCHAR2(20),
    new_status    VARCHAR2(20) NOT NULL,
    timestamp     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_log_container FOREIGN KEY (container_id)
        REFERENCES containers (container_id)
        ON DELETE CASCADE
);

-- ============================================================================
-- TABLE: resource_usage
-- Time-series telemetry tracking real-time CPU% and Memory consumption
-- ============================================================================
CREATE TABLE resource_usage (
    usage_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    container_id  NUMBER NOT NULL,
    cpu_usage     NUMBER(5, 2) DEFAULT 0.00 NOT NULL,   -- e.g. 12.50 %
    memory_usage  NUMBER(12, 2) DEFAULT 0.00 NOT NULL,  -- In Megabytes (MB)
    recorded_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_usage_container FOREIGN KEY (container_id)
        REFERENCES containers (container_id)
        ON DELETE CASCADE
);

-- ============================================================================
-- PERFORMANCE & INTEGRITY INDEXES
-- ============================================================================
-- Index on foreign keys to prevent full table locks during parent table deletion
CREATE INDEX idx_process_logs_cid ON process_logs (container_id);
CREATE INDEX idx_resource_usage_cid ON resource_usage (container_id);

-- Indexes for frequent query filters in CLI operations (ps, health checks)
CREATE INDEX idx_containers_status ON containers (status);
CREATE INDEX idx_containers_pid ON containers (pid);

COMMIT;
